### ISSUE TITLE
No Fonts for Dialog boxes

### ISSUE THREAD

**Issue by justlikekevin** [erikstricker/PDE#5]
Windows 10 user here. When I try to use PDE_analyzer_i() for example, every dialog box I get that uses system fonts doesn't have any words. Wondering if there is a font I need to download or if the default might be broken.

**Comment by erikstricker** [comment]
That is interesting. The font used by the PDE is Arial:
```
if (Sys.info()["sysname"] == "Windows") {
    os.font <- "Arial"
    os.font.ten.bold <- "Arial 10 bold"
    os.font.twelve.bold <- "Arial 12 bold"
}
```
Could you check that the output of `Sys.info()["sysname"]` is Windows? Also, a screenshot of the issue would help as well.

Lastly, below is the code to generate the tooltip. If you run that there should be a ? with a tooltip.


```
library(tcltk)
library(tcltk2)
tooltip <- function(text, targetWidget, width = 350){
    end <- function(){
      tkdestroy(base)
    }
    tipX <- as.numeric(tkwinfo("rootx", targetWidget)) +
      as.numeric(tkwinfo("width", targetWidget))
    tipY <- as.numeric(tkwinfo("rooty", targetWidget))
    # Takes out the frame and title bar
    tkwm.overrideredirect(base <- tktoplevel(), TRUE)
    on.exit(tkdestroy(base))
    # Put the TW in the right place
    tkwm.geometry(base, paste("+", tipX, "+", tipY, sep = ""))
    tip <- tklabel(base, text = text, background = "white",
                   wraplength = width)
    tkpack(tip)
    tkbind(targetWidget, "<Leave>", end)
    tkwait.window(base)
    return(invisible())
  }

os.font.ten.underlined <- "Arial 10 underline"
tt <- tktoplevel()
l7.hint_choosepdf <- tcltk2::tk2label(tt, text = "?",
                                          font = os.font.ten.underlined,
                                          background = "#05F2C7",
                                          foreground="blue")

tcltk::tkbind(l7.hint_choosepdf, "<Enter>",
                  expression(tooltip(paste0("Choose a folder with PDF files or ",
                                            "select one or more PDF files for analysis ",
                                            "(use Ctrl and/or Shift to select multiple). ",
                                            "All PDF files in the chosen folder and ",
                                            "subfolders will be analyzed. ",
                                            "Multiple PDF files will be separated by \";\" without a space."),
                                     l7.hint_choosepdf)))
  tkpack(l7.hint_choosepdf) # geometry manager
```

**Comment by justlikekevin** [comment]
sysname 
"Windows" 
![PDE font issue screenshot - Copy](https://github.com/erikstricker/PDE/assets/142857599/0616a17d-4511-4ac9-8274-961f2b69470a)

**Comment by justlikekevin** [comment]
I think I may have figured out part of it. It looks like RStudio is finding a conflict with my fonts, but I don't know which fonts are the problem or how to fix it yet. It's not your package specifically, even base file.choose() has the problem.

**Comment by erikstricker** [comment]
Here a potential solution from stackoverflow (https://stackoverflow.com/questions/76045274/file-choose-dialogue-box-is-blank):

You would need to execute as the very first command of a fresh R session `choose.files()`. This will cache the fonts. Later calls to `choose.files()` or `file.choose()` will usually work fine and show all fonts.

**Comment by erikstricker** [comment]
And 4 more solutions (https://stackoverflow.com/questions/75892124/file-choose-opens-dialogue-without-file-names-on-windows):

Firstly, as Mikael Jagan stated, try running base::file.choose() from the command line, rather than from RStudio. If this works well, try upgrading R to the latest version. It should be at least 4.3.0, but at the moment of writing we are in R 4.3.1 for which it should work too. Then, file.choose and choose.files are up to date enough.

Secondly, if this does not work, open the app 'file explorer' and keep it open while using the file.choose function in RStudio.

Thirdly, if the problem still persists, check if your RStudio file chooser is currently located to a path which is accessible. If you last opened a file to which the path is now depricated, the file chooser might struggle with opening any path at all. You can solve this by manually opening a random file by using Ctrl + O and clicking some random file. Then retry file.choose.

Fourthly, you might consider to reboot your pc/RStudio. This may work only after multiple times; do not give up too soon.

**Comment by justlikekevin** [comment]
I think this is what is going on, but I can't seem to figure out how to run this code. https://github.com/rstudio/rstudio/issues/13007#issuecomment-1523088511

I also have had problems for awhile getting rstudio to load up, and i it seems like electron has been an issue, because i have been able to clear some error messages by closing tasks.

**Comment by justlikekevin** [comment]
On the other workarounds. I've got 4.4.0, file explorer is open, i can open a file using CTRL-O - i haven't done multiple reboots yet, it really seems like a font/electron/npm issue

**Comment by justlikekevin** [comment]
forgot to mention- the choose.files() when loading R doesn't work and I just tried the R command line and choose.files() and file.choose() both work fine there

**Comment by erikstricker** [comment]
At this point, it seems that this issue is associated with RStudio and not the PDE package. Therefore, I will close the issue.

Current workarounds that let's you still use the PDE package are:
1) Use the R command line to start the `PDE_analyzer_i()`
2) Use the `PDE_analyzer_i()` in RStudio and manually enter the desired file locations
3) Use the `PDE_analyzer()`

Best
Erik
